[build]
base = ""
command = """
pip install --upgrade pip \
&& pip install --upgrade --upgrade-strategy eager  -e ".[docs]" \
&& pip install git+https://oauth:${MKDOCS_MATERIAL_INSIDERS_REPO_RO}@github.com/PrefectHQ/mkdocs-material-insiders.git@master \
&& mkdocs build --config-file mkdocs.insiders.yml \
"""
publish = "site"