name: Build Docs

on:
  pull_request:

env:
  MKDOCS_SOCIAL_CARDS: ${{ vars.MKDOCS_SOCIAL_CARDS }}
  MKDOCS_INSIDERS_PATH: ${{ secrets.MKDOCS_INSIDERS_PATH }}

permissions:
  contents: write
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      # for now, only install mkdocs. In the future may need to install Marvin itself.
      - name: Install dependencies for MKDocs Material
        run: pip install \
          git+https://oauth:${MKDOCS_INSIDERS_PAT}@github.com/PrefectHQ/mkdocs-material-insiders.git \
          mkdocs-autolinks-plugin \
          mkdocs-awesome-pages-plugin \
          mkdocstrings[python] \
          pillow \
          cairosvg
      - name: Build docs
        run: |
          mkdocs build --config-file mkdocs.insiders.yml