name: Build Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'mkdocs.insiders.yml'
      - '.github/workflows/build-docs.yml'


env:
  MKDOCS_SOCIAL_CARDS: ${{ vars.MKDOCS_SOCIAL_CARDS }}
  MKDOCS_MATERIAL_INSIDERS_REPO_RO: ${{ secrets.MKDOCS_MATERIAL_INSIDERS_REPO_RO }}

permissions:
  contents: write
jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install uv
        run: pip install -U uv && uv venv
      
      - name: Install Material Insiders
        run: pip install git+https://oauth:${MKDOCS_MATERIAL_INSIDERS_REPO_RO}@github.com/PrefectHQ/mkdocs-material-insiders.git

      # for now, only install mkdocs. In the future may need to install Marvin itself.
      - name: Install dependencies for MKDocs Material
        run: uv pip install \
          mkdocs-autolinks-plugin \
          mkdocs-awesome-pages-plugin \
          mkdocs-markdownextradata-plugin \
          mkdocstrings[python] \
          pillow \
          cairosvg
      - name: Build docs
        run: |
          mkdocs build --config-file mkdocs.insiders.yml