# Basic tests run on every PR and merges to main

name: Run tests

env:
  # enable colored output
  # https://github.com/pytest-dev/pytest/issues/7443
  PY_COLORS: 1

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/run-tests.yml
      - src/**
      - tests/**
      - pyproject.toml
      - setup.py

  pull_request:
    paths:
      - .github/workflows/run-tests.yml
      - src/**
      - tests/**
      - pyproject.toml
      - setup.py

  workflow_dispatch:

permissions:
  contents: read

jobs:

  run_basic_tests:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    env:
      MARVIN_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/pyproject.toml"
      - name: Install Marvin
        run: |
          pip install ".[dev,chromadb]"
      - name: Run tests that don't require LLMs
        run: |
          pytest -v -m "not llm"