name: Run Tests

env:
  # enable colored output
  # https://github.com/pytest-dev/pytest/issues/7443
  PY_COLORS: 1

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/run-tests.yml
      - src/**
      - tests/**
      - pyproject.toml
      - setup.py

  pull_request:
    paths:
      - .github/workflows/run-tests.yml
      - src**
      - tests/**
      - pyproject.toml
      - setup.py

  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_tests:
    name: ${{ matrix.test-type }} w/ python ${{ matrix.python-version }} on ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
        include:
          - python-version: '3.9'
            test-type: 'llm'
          - python-version: '3.9'
            test-type: 'not llm'
          - python-version: '3.10'
            test-type: 'not llm'
          - python-version: '3.11'
            test-type: 'not llm'

    runs-on: ${{ matrix.os }}

    env:
      MARVIN_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install Marvin
        run: pip install ".[dev]"
      - name: Run ${{ matrix.test-type }} tests
        run: pytest -vv -m "${{ matrix.test-type }}"